add_test([=[RTP.NO_FAILURE]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.NO_FAILURE]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.NO_FAILURE]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.NO_FAILURE_OPT]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.NO_FAILURE_OPT]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.NO_FAILURE_OPT]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.RECEIVER_TEST_LOST_DATA]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.RECEIVER_TEST_LOST_DATA]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.RECEIVER_TEST_LOST_DATA]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.RECEIVER_TEST_DUP_DATA]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.RECEIVER_TEST_DUP_DATA]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.RECEIVER_TEST_DUP_DATA]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.RECEIVER_TEST_WRONG_CHKSUM_DATA]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.RECEIVER_TEST_WRONG_CHKSUM_DATA]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.RECEIVER_TEST_WRONG_CHKSUM_DATA]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.RECEIVER_TEST_REORDER_DATA]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.RECEIVER_TEST_REORDER_DATA]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.RECEIVER_TEST_REORDER_DATA]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.RECEIVER_TEST_MIXED_1]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.RECEIVER_TEST_MIXED_1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.RECEIVER_TEST_MIXED_1]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.RECEIVER_TEST_MIXED_2]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.RECEIVER_TEST_MIXED_2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.RECEIVER_TEST_MIXED_2]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.SENDER_TEST_LOST_ACK]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.SENDER_TEST_LOST_ACK]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.SENDER_TEST_LOST_ACK]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.SENDER_TEST_DUP_ACK]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.SENDER_TEST_DUP_ACK]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.SENDER_TEST_DUP_ACK]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.SENDER_TEST_WRONG_CHKSUM_ACK]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.SENDER_TEST_WRONG_CHKSUM_ACK]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.SENDER_TEST_WRONG_CHKSUM_ACK]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.SENDER_TEST_REORDER_ACK]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.SENDER_TEST_REORDER_ACK]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.SENDER_TEST_REORDER_ACK]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.SENDER_TEST_MIXED_1]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.SENDER_TEST_MIXED_1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.SENDER_TEST_MIXED_1]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.SENDER_TEST_MIXED_2]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.SENDER_TEST_MIXED_2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.SENDER_TEST_MIXED_2]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.OPT_RECEIVER_TEST_LOST_DATA]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.OPT_RECEIVER_TEST_LOST_DATA]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.OPT_RECEIVER_TEST_LOST_DATA]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.OPT_RECEIVER_TEST_DUP_DATA]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.OPT_RECEIVER_TEST_DUP_DATA]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.OPT_RECEIVER_TEST_DUP_DATA]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.OPT_RECEIVER_TEST_WRONG_CHKSUM_DATA]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.OPT_RECEIVER_TEST_WRONG_CHKSUM_DATA]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.OPT_RECEIVER_TEST_WRONG_CHKSUM_DATA]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.OPT_RECEIVER_TEST_REORDER_DATA]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.OPT_RECEIVER_TEST_REORDER_DATA]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.OPT_RECEIVER_TEST_REORDER_DATA]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.OPT_RECEIVER_TEST_MIXED_1]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.OPT_RECEIVER_TEST_MIXED_1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.OPT_RECEIVER_TEST_MIXED_1]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.OPT_RECEIVER_TEST_MIXED_2]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.OPT_RECEIVER_TEST_MIXED_2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.OPT_RECEIVER_TEST_MIXED_2]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.OPT_SENDER_TEST_LOST_ACK]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.OPT_SENDER_TEST_LOST_ACK]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.OPT_SENDER_TEST_LOST_ACK]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.OPT_SENDER_TEST_DUP_ACK]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.OPT_SENDER_TEST_DUP_ACK]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.OPT_SENDER_TEST_DUP_ACK]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.OPT_SENDER_TEST_WRONG_CHKSUM_ACK]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.OPT_SENDER_TEST_WRONG_CHKSUM_ACK]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.OPT_SENDER_TEST_WRONG_CHKSUM_ACK]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.OPT_SENDER_TEST_REORDER_ACK]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.OPT_SENDER_TEST_REORDER_ACK]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.OPT_SENDER_TEST_REORDER_ACK]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.OPT_SENDER_TEST_MIXED_1]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.OPT_SENDER_TEST_MIXED_1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.OPT_SENDER_TEST_MIXED_1]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RTP.OPT_SENDER_TEST_MIXED_2]=]  /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test/rtp_test_all [==[--gtest_filter=RTP.OPT_SENDER_TEST_MIXED_2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RTP.OPT_SENDER_TEST_MIXED_2]=]  PROPERTIES WORKING_DIRECTORY /home/aaa/Desktop/lab2-rtp-zyt600/Lab2-RTP-Test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  rtp_test_all_TESTS RTP.NO_FAILURE RTP.NO_FAILURE_OPT RTP.RECEIVER_TEST_LOST_DATA RTP.RECEIVER_TEST_DUP_DATA RTP.RECEIVER_TEST_WRONG_CHKSUM_DATA RTP.RECEIVER_TEST_REORDER_DATA RTP.RECEIVER_TEST_MIXED_1 RTP.RECEIVER_TEST_MIXED_2 RTP.SENDER_TEST_LOST_ACK RTP.SENDER_TEST_DUP_ACK RTP.SENDER_TEST_WRONG_CHKSUM_ACK RTP.SENDER_TEST_REORDER_ACK RTP.SENDER_TEST_MIXED_1 RTP.SENDER_TEST_MIXED_2 RTP.OPT_RECEIVER_TEST_LOST_DATA RTP.OPT_RECEIVER_TEST_DUP_DATA RTP.OPT_RECEIVER_TEST_WRONG_CHKSUM_DATA RTP.OPT_RECEIVER_TEST_REORDER_DATA RTP.OPT_RECEIVER_TEST_MIXED_1 RTP.OPT_RECEIVER_TEST_MIXED_2 RTP.OPT_SENDER_TEST_LOST_ACK RTP.OPT_SENDER_TEST_DUP_ACK RTP.OPT_SENDER_TEST_WRONG_CHKSUM_ACK RTP.OPT_SENDER_TEST_REORDER_ACK RTP.OPT_SENDER_TEST_MIXED_1 RTP.OPT_SENDER_TEST_MIXED_2)
